# Rest Client tutorial: https://www.youtube.com/watch?v=RcxvrhQKv8I

### Get all countries
GET http://localhost:5000/api/countries

### Get all country by id
GET http://localhost:5000/api/country/1


### Get all cities
GET http://localhost:5000/api/cities

### Get all city by id
GET http://localhost:5000/api/city/1


### Get all counties
GET http://localhost:5000/api/counties

###Get counties by id
GET http://localhost:5000/api/county/1